# SITE CONFIGURATION
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rageandqq.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Sameer Chitley
  icon: <i class="fa fa-2x fa-home"></i>
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text_feature_image: "img/bg.png"
  footer_text: >
    Made with <i class="fa fa-fw fa-heart" color="#f00"></i> in Waterloo, Canada

  # Icons
  email_address: schitley@edu.uwaterloo.ca # Full email address, e.g. "sam@example.com"
  # dribbble:
  github: "rageandqq"
  linkedin: "https://ca.linkedin.com/in/sameerchitley" # Full URL
  stack_overflow: "https://stackoverflow.com/users/3133680/rageandqq" # Full URL
  twitter: "rageandqq"

  # Scripts
  # google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: rageandqq
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
